#ifndef ITEMS_H
#define ITEMS_H 1

#include "Shield.h"
#include "ClassMod.h"
#include "Grenade.h"
#include "Weapon.h"
#include "Relic.h"

char* fileHeader = {
        "###\n### Item Randomizer\n### WARNING: THIS IS VERY BUGGY!\n### Generated by mkitemrand\n"
};

char* fileFooter = {
        "\n### That's all folks!\n"
};

#endif
