#ifndef ITEMS_H
#define ITEMS_H 1

#include "Shield.h"
#include "ClassMod.h"
#include "Grenade.h"
#include "Weapon.h"
#include "Relic.h"

char* fileHeader = {
        "###\r\n### Item Randomizer\r\n### Originally by SSpyR, enhanced by HackerSmacker\r\n### Generated by mkitemrand\r\n"
};

char* fileFooter = {
        "\r\n### That's all folks!\r\n"
};

#endif
